job/urls.py
from django.urls import path,include
from . import views
from . import api



app_name='job'

urlpatterns = [
    path('',views.jop_list,name='job_list'), 
    path('add/', views.add_job,name='add_job'),
    path('<str:slug>', views.job_detail,name='job_detils'),
    
    

    #API 
    path('api/list/<int:id>', api.Job_List_Api.as_view(), name='Job_List_Api'),
    path('api/list/v2/', api.Job_Create_Api.as_view(), name='Job_Create_Api'),
    

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    # Add this for language prefix in URLs
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns (
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('jobs/',include('job.urls',namespace='jobs')),
    path('contact-us/',include('contact.urls',namespace='contact')),
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('api-auth/', include('rest_framework.urls'))
    

    
    
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
prefix_default_language=False  # This makes the default language URL appear without prefix

job/models.py
from django.db import models
from django.utils.text import slugify
from django_countries.fields import CountryField
from django.contrib.auth.models import User

# Create your models here.

JOB_TYPE=(
    ('Full Time','Full Time'),
    ('Part Time','Part Time'),
)

def image_upload(instance,filename):
    imagename,extention=filename.split(".")
    return 'jobs/%s.%s'%(instance.id,extention)
    

class Job(models.Model):
    owner=models.ForeignKey(User,related_name='job_owner',on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    job_tybe=models.CharField(max_length=15,choices=JOB_TYPE)
    country = models.CharField(
        max_length=200,
        null=True,
        choices=list(CountryField().choices) + [('', 'Select Country')]
    ) # Add the country field

    description=models.TextField(max_length=10000)

    responsibilities = models.TextField(max_length=10000)
    qualifications = models.TextField(max_length=10000)
    benefits = models.TextField(max_length=10000)
    published_at=models.DateTimeField(auto_now=True)
    Vacancy=models.IntegerField(default=1)
    
    salary=models.IntegerField(default=0)
    experince=models.IntegerField(default=1)
    #category
    category = models.ForeignKey('Category',on_delete=models.CASCADE)
    image=models.ImageField(upload_to=image_upload)
    slug=models.SlugField(blank=True,null=True)
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(Job,self).save(*args,**kwargs)
        
    def __str__(self): 
        return self.title
# متنساش لما user يبقه عامل signin ميظهرلوش غير apply
class Category(models.Model):
    name=models.CharField(max_length=25)
    
    def __str__(self): 
        return self.name
    
    
# متنساش الترجمه 
class Apply(models.Model):
    job=models.ForeignKey(Job, related_name='apply_job', on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    email=models.EmailField(max_length=100)
    website=models.URLField(null=True,blank=True)
    cv=models.FileField(upload_to='apply/',)
    cover_letter=models.TextField(max_length=500)
    created_at=models.DateTimeField(auto_now=True)
    
     
    
    def __str__(self):
        return self.name
    


    

job/forms.py
from django import forms
from .models import Apply,Job

class ApplyForm(forms.ModelForm):
    class Meta: 
        model=Apply
        fields=['name','email','website','cv','cover_letter']
        
class Jobform(forms.ModelForm):
    class Meta:
        model=Job
        fields='__all__'
        exclude=('owner','slug')
    

job/views.py
from audioop import reverse
from .filters import JobFilter
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from .models import Job
from .forms import ApplyForm,Jobform
from django.contrib import messages
from django.utils.translation import gettext as _


from django.contrib.auth.decorators import login_required

# Create your views here.

def jop_list(request):
    job_list = Job.objects.all()
    myfilter = JobFilter(request.GET, queryset=job_list)
    job_list = myfilter.qs
    paginator = Paginator(job_list, 3) 
    page_number = request.GET.get('page')
    job_list = paginator.get_page(page_number)
    context = {'job_list': job_list, 'myfilter': myfilter}
    
    # Translated message
    messages.success(request, _('Congratulations! The job has been successfully posted. We look forward to receiving qualified candidates!'))
    return render(request, 'job/job_list.html', context)

def job_detail(request, slug):
    job_detail = Job.objects.get(slug=slug)
    context = {'job_detail': job_detail}  # Define context outside the else block

    if request.method == 'POST':
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.job = job_detail
            myform.save()
            messages.success(request, 'Applying for the job was successful!')
            request.session['show_message'] = True  # Set session variable

            return redirect('jobs:job_list')
    else:
        form = ApplyForm()

    context['form'] = form  # Update the context with the 'form' variable
    
    # In your Django view
    request.session.pop('show_message', None)


    return render(request, 'job/job_detils.html', context)


@login_required
def add_job(request):
    if request.method=='POST':
        form=Jobform(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.owner=request.user
            myform.save()
            
            messages.success(request, 'Congratulations! The job has been successfully posted. We look forward to receiving qualified candidates!')
            request.session['show_message'] = True  # Set session variable
            return redirect('jobs:job_list')


            
    else:
        form=Jobform()
        
    context = {
            
        'form':form
         
        }
    request.session.pop('show_message', None)

    
    return render(request,'job/add_job.html',context)


# ChatBot

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body%}


{% if messages %}
    {% for message in messages %}
        <div id="success-message" style="display: {% if request.session.show_message %}block{% else %}none{% endif %}; color: green;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var successMessage = document.getElementById('success-message');
        
        if (successMessage) {
            // JavaScript to hide the message after 5 seconds
            setTimeout(function () {
                successMessage.style.display = 'none';
            }, 5000);  // 5 seconds = 5 * 1000 milliseconds
        }
    });
</script>


    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3 class="wow fadeInLeft" data-wow-duration="1s">Add New Job</h3>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    
                    <div class="apply_job_form white-bg">
                        <h4>Post New Job</h4>
                        <form  method="POST"class="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        {% buttons %}
                         <button class="boxed-btn3 w-100"> Post Now</button>
                        {% endbuttons %}
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
{% endblock body %}

job/templates/job/job_detils.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% block body %}
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3 class="wow fadeInLeft" data-wow-duration="1s">{{job_detail}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="job_details_area">
        <div class="container">
            <div class="row {% if LANGUAGE_CODE == 'ar' %}flex-row-reverse{% endif %}">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between {% if LANGUAGE_CODE == 'ar' %}flex-row-reverse{% endif %}">
                            <div class="jobs_left d-flex align-items-center {% if LANGUAGE_CODE == 'ar' %}flex-row-reverse{% endif %}">
                                <div class="thumb">
                                    <img src="{% static 'img/svg_icon/1.svg' %}" alt="">
                                </div>
                                <div class="jobs_conetent {% if LANGUAGE_CODE == 'ar' %}me-3{% else %}ms-3{% endif %}">
                                    <a href="#"><h4>{{job_detail}}</h4></a>
                                    <div class="links_locat d-flex align-items-center {% if LANGUAGE_CODE == 'ar' %}flex-row-reverse{% endif %}">
                                        <div class="location">
                                            <p><i class="fa fa-map-marker"></i> {{job_detail.country}}</p>
                                        </div>
                                        <div class="location {% if LANGUAGE_CODE == 'ar' %}me-3{% else %}ms-3{% endif %}">
                                            <p><i class="fa fa-clock-o"></i> {{job_detail.job_tybe}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"><i class="ti-heart"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg text-{{ LANGUAGE_CODE|default:'left' }}">
                        <div class="single_wrap">
                            <h4>{% trans "Job description" %}</h4>
                            <p>{{job_detail.description}}</p>
                        </div>
                        <div class="single_wrap">
                            <h4>{% trans "Responsibility" %}</h4>
                            <p>{{job_detail.responsibilities}}</p>
                        </div>
                        <div class="single_wrap">
                            <h4>{% trans "Qualifications" %}</h4>
                            <p>{{job_detail.qualifications}}</p>
                        </div>
                        <div class="single_wrap">
                            <h4>{% trans "Benefits" %}</h4>
                            <p>{{job_detail.benefits}}</p>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>{% trans "Apply for the job" %}</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}
                            <button class="boxed-btn3 w-100" type="submit">{% trans "Apply Now" %}</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>{% trans "Job Summary" %}</h3>
                        </div>
                        <div class="job_content text-{{ LANGUAGE_CODE|default:'left' }}">
                            <ul>
                                <li>{% trans "Published on:" %} <span>{{job_detail.published_at|date:'d M o'}}</span></li>
                                <li>{% trans "Vacancy:" %} <span>{{job_detail.Vacancy}} {% trans "Position" %}</span></li>
                                <li>{% trans "Salary:" %} <span>{{job_detail.salary}} {% trans "k/y" %}</span></li>
                                <li>{% trans "Location:" %} <span>{{job_detail.country}}</span></li>
                                <li>{% trans "Job Nature:" %} <span>{{job_detail.job_tybe}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex {% if LANGUAGE_CODE == 'ar' %}flex-row-reverse{% endif %}">
                        <span>{% trans "Share at:" %}</span>
                        <ul class="{% if LANGUAGE_CODE == 'ar' %}me-3{% else %}ms-3{% endif %}">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                                function initMap() {
                                    var uluru = {lat: -25.363, lng: 131.044};
                                    var grayStyles = [
                                        {
                                            featureType: "all",
                                            stylers: [
                                                { saturation: -90 },
                                                { lightness: 50 }
                                            ]
                                        },
                                        {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                    ];
                                    var map = new google.maps.Map(document.getElementById('map'), {
                                        center: {lat: -31.197, lng: 150.744},
                                        zoom: 9,
                                        styles: grayStyles,
                                        scrollwheel: false
                                    });
                                }
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

job/templates/job/job_list.html
{% extends 'base.html' %}
    <!-- bradcam_area  -->
    {% load bootstrap4 %}
    {% load static %}
    {% load i18n %}
    
    {% block body %}


    {% if messages %}
    {% for message in messages %}
        <div id="success-message" style="display: {% if request.session.show_message %}block{% else %}none{% endif %}; color: green;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var successMessage = document.getElementById('success-message');
        
        if (successMessage) {
            // JavaScript to hide the message after 5 seconds
            setTimeout(function () {
                successMessage.style.display = 'none';
            }, 5000);  // 5 seconds = 5 * 1000 milliseconds
        }
    });
</script>
<script type="text/javascript">
    (function(d, m){
        var kommunicateSettings = 
            {"appId":"13aad466ad65ba5fdae2167cf6156f59a","popupWidget":true,"automaticChatOpenOnNavigation":true};
        var s = document.createElement("script"); s.type = "text/javascript"; s.async = true;
        s.src = "https://widget.kommunicate.io/v2/kommunicate.app";
        var h = document.getElementsByTagName("head")[0]; h.appendChild(s);
        window.kommunicate = m; m._globals = kommunicateSettings;
    })(document, window.kommunicate || {});
/* NOTE : Use web server to view HTML files as real-time update will not work if you directly open the HTML file in the browser. */
</script>
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">

                        <h3 class="wow fadeInLeft" data-wow-duration="1s">
                            {% blocktrans count counter=job_list|length %}
                                {{ counter }} Job Available
                            {% plural %}
                                {{ counter }} Jobs Available
                            {% endblocktrans %}
                        </h3>                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form myfilter.form %}

                                <input type ="submit" value="Search" class="boxed-btn3 w-100 mt-2">
                                
                            </form>
                        </div>
                        <div class="reset_btn">
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h2>Job Listing</h2>
                                </div>
                                
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in job_list %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="{% static 'img/svg_icon/1.svg' %}" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_detils' job.slug %}"><h4>{{job}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{job.country}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.job_tybe}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_detils' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>{{job.published_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                           {% endfor %}
                        </div>
                        {% if job_list.has_other_pages%}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if job_list.has_previous %}


                                        <li><a href="?pages={{job_list.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {%endif%}

                                        {% for i in job_list.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {%endfor%}
                                        
                                        

                                        {% if job_list.has_next %}
                                        <li><a href="?pages={{job_list.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {%endif%}

                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- job_listing_area_end  -->

    {% endblock body %}
   
    