accounts/urls.py
from django.urls import path,include
from . import views
app_name='accounts'

urlpatterns = [
    path('signup',views.signup,name='signup'), 
    path('profile/',views.profile,name='profile'), 
    path('profile/edit',views.profile_edit,name='profile_edit'), 
    
]

job/urls.py
from django.urls import path,include
from . import views
from . import api



app_name='job'

urlpatterns = [
    path('',views.jop_list,name='job_list'), 
    path('add/', views.add_job,name='add_job'),
    path('<str:slug>', views.job_detail,name='job_detils'),
    
    

    #API 
    path('api/list/<int:id>', api.Job_List_Api.as_view(), name='Job_List_Api'),
    path('api/list/v2/', api.Job_Create_Api.as_view(), name='Job_Create_Api'),
    

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    # Add this for language prefix in URLs
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns (
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('jobs/',include('job.urls',namespace='jobs')),
    path('contact-us/',include('contact.urls',namespace='contact')),
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('api-auth/', include('rest_framework.urls'))
    

    
    
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
prefix_default_language=False  # This makes the default language URL appear without prefix

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    city=models.ForeignKey('City',related_name='user_city',on_delete=models.CASCADE,blank=True, null=True)
    phone_number=models.CharField(max_length=15, blank=True, null=True)
    image=models.ImageField(upload_to='profile/')
    
    def __str__(self):
           return str(self.user)
       
@receiver(post_save,sender=User)      
def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile=Profile.objects.create(user=kwargs['instance'])
    post_save.connect(create_profile,sender=User)


class City(models.Model):
    name=models.CharField(max_length=30)
    def __str__(self):
           return (self.name)
       
       

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile



class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2'] 
        
class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['city','phone_number','image']

accounts/views.py
from urllib import request
from django.shortcuts import redirect, render
from .forms import SignupForm,UserForm,ProfileForm
from django.contrib.auth import authenticate,login
from .models import Profile
from django.urls import reverse


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']  # Use 'password1' here
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/accounts/profile')
    else:
        form = SignupForm()

    return render(request, 'registration/signup.html', {'form': form})


def profile(request):
    profile=Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        userform = UserForm(request.POST, instance=request.user)
        profleform = ProfileForm(request.POST, request.FILES, instance=profile)  # Include request.FILES for image uploads
        if userform.is_valid() and profleform.is_valid():
            userform.save()
            profleform.save()
            return redirect(reverse('accounts:profile'))
    else:
        userform = UserForm(instance=request.user)
        profleform = ProfileForm(instance=profile)
    
    return render(request, 'accounts/profile_edit.html', {'userform': userform, 'profleform': profleform})

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block body%}


    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-8 mx-auto">
                    <div class="Profile_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                            <hr>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <br>

                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <br>

                                <li>phone_number: <span>{{profile.phone_number}}</span></li>
                                <br>

                                <li>Address:<span>{{profile.city}}</span></li>
                                <br>

                            </ul>
                        </div>
                        <div class="p-5">
                            <a class="boxed-btn3 w-100" href="{% url 'accounts:profile_edit' %}">Profile Edit</a>
                    </div>
                    
                   
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block body%}


    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
           
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    
                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form  method="POST"class="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form profleform %}
                        {% buttons %}
                         <button class="boxed-btn3 w-100"> Save </button>
                        {% endbuttons %}
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
{% endblock body %}